(function(){'use strict';
const managers=new Set(['HSA','OSA','ADMIN','SUPERVISOR']);
const isManager=()=>managers.has(String(window.INJOKO_ROLE||'').toUpperCase());
const labels={daily:'HARIAN',weekly:'MINGGUAN',all:'KESELURUHAN'};
function css(){if(document.getElementById('hsaPeriodCss'))return;const s=document.createElement('style');s.id='hsaPeriodCss';s.textContent='.hsa-dashboard-period{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:0 0 12px;padding:5px;border:1px solid rgba(123,160,200,.16);border-radius:15px;background:rgba(5,14,25,.72)}.hsa-dashboard-period button{border:0;border-radius:10px;padding:10px 4px;background:transparent;color:#7890a9;font-size:10px;font-weight:900}.hsa-dashboard-period button.active{background:linear-gradient(135deg,#1c83ff,#4fd7ff);color:#fff;box-shadow:0 5px 18px rgba(36,135,255,.2)}.hsa-leader-period{margin:0 0 9px;color:#7f95ad;font-size:10px}.hsa-leader-period b{color:#dceaff}';document.head.appendChild(s)}
function existingPeriod(p){return document.querySelector('.period[data-period="'+p+'"]')}
function setActive(p){document.querySelectorAll('.hsa-dashboard-period button').forEach(b=>b.classList.toggle('active',b.dataset.period===p));const n=document.getElementById('hsaLeaderPeriod');if(n)n.innerHTML='Periode leaderboard: <b>'+labels[p]+'</b>';const pill=document.getElementById('periodPillLabel');if(pill)pill.textContent=p==='daily'?'Hari Ini':p==='weekly'?'Minggu Ini':'Keseluruhan'}
function install(){if(!isManager())return;const dash=document.getElementById('dashboardPage');const kpi=document.querySelector('#dashboardPage .kpi-grid');if(!dash||!kpi)return;let box=document.getElementById('hsaDashboardPeriod');if(!box){box=document.createElement('div');box.id='hsaDashboardPeriod';box.className='hsa-dashboard-period';box.innerHTML=Object.keys(labels).map(p=>'<button type="button" data-period="'+p+'">'+labels[p]+'</button>').join('');kpi.parentNode.insertBefore(box,kpi);box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const target=existingPeriod(b.dataset.period);if(target)target.click();setActive(b.dataset.period)}));}const current=document.querySelector('.period.active')?.dataset.period||'daily';setActive(current);const lp=document.querySelector('.leaderboard-panel .panel-head');if(lp&&!document.getElementById('hsaLeaderPeriod')){const n=document.createElement('p');n.id='hsaLeaderPeriod';n.className='hsa-leader-period';lp.parentNode.insertBefore(n,document.querySelector('#leaderboard-panel')||lp.nextSibling);}
const panel=document.querySelector('.leaderboard-panel');if(panel&&!document.getElementById('hsaLeaderPeriod')){const n=document.createElement('p');n.id='hsaLeaderPeriod';n.className='hsa-leader-period';panel.insertBefore(n,panel.querySelector('.search-wrap')||panel.firstChild);}
setActive(document.querySelector('.period.active')?.dataset.period||'daily');
}
function hook(){document.addEventListener('click',e=>{if(!isManager())return;const p=e.target.closest('.period');if(p)setTimeout(()=>setActive(p.dataset.period||'daily'),20);const nav=e.target.closest('[data-page],[data-drawer-page]');if(nav&&(nav.dataset.page||nav.dataset.drawerPage)==='dashboardPage')setTimeout(install,80)});const o=new MutationObserver(()=>{if(isManager())install()});o.observe(document.body,{childList:true,subtree:true});}
function boot(){css();install();hook()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();