(() => {
  if (window.__technicianMasterUiInstalled) return;
  window.__technicianMasterUiInstalled = true;
  let payload=null;
  function styles(){if(document.querySelector('#technicianMasterStyles'))return;const s=document.createElement('style');s.id='technicianMasterStyles';s.textContent=`.tm-open{width:100%;margin-top:10px;border:1px solid #2c6a8e;background:#0b263a;color:#eaf7ff;border-radius:12px;padding:11px;font-weight:800;font-size:11px}.tm-overlay{position:fixed;inset:0;z-index:260;background:#06111f;overflow:auto;padding:env(safe-area-inset-top) 14px 110px}.tm-head{position:sticky;top:0;z-index:2;background:#06111f;padding:16px 0 12px;display:flex;align-items:center;gap:10px}.tm-head button{border:1px solid #294a68;background:#0b1b2d;color:#fff;border-radius:50%;width:42px;height:42px;font-size:22px}.tm-head div{flex:1}.tm-head strong{display:block;font-size:20px}.tm-head small{color:#7f96ad}.tm-tools{display:flex;gap:8px;margin-bottom:12px}.tm-tools input{flex:1;min-width:0;border:1px solid #294a68;background:#091827;color:#eef7ff;border-radius:12px;padding:11px}.tm-tools button,.tm-save{border:1px solid #2d78a4;background:#0b2a40;color:#eaf7ff;border-radius:12px;padding:10px 12px;font-weight:800}.tm-card{border:1px solid #29445f;background:linear-gradient(180deg,#0c1d30,#091624);border-radius:16px;padding:13px;margin:9px 0}.tm-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.tm-field{display:block}.tm-field.wide{grid-column:1/-1}.tm-field span{display:block;color:#7e94aa;font-size:8px;margin:0 0 4px}.tm-field input{width:100%;box-sizing:border-box;border:1px solid #2d4965;background:#081725;color:#eef7ff;border-radius:10px;padding:9px;font-size:11px}.tm-meta{color:#6f879e;font-size:9px;margin:7px 0}.tm-save{width:100%;margin-top:9px}.tm-stat{font-size:10px;color:#55d9ff;margin-bottom:10px}.tm-warn{color:#ffbf66;font-size:9px;margin-top:6px}`;document.head.appendChild(s);}
  function userId(){return String(telegramUser()?.id||'').trim();}
  async function loadMaster(){const id=userId();if(!id)throw new Error('Mini App harus dibuka dari Telegram.');const r=await fetch(`/api/technician-master?${new URLSearchParams({telegram_id:id})}`,{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||`HTTP ${r.status}`);payload=d;return d;}
  function card(item,index){return `<article class="tm-card" data-tm-index="${index}" data-original-nik="${esc(item.nik||'')}"><div class="tm-grid"><label class="tm-field"><span>NIK • dapat dikoreksi admin</span><input name="nik" inputmode="numeric" value="${esc(item.nik||'')}"></label><label class="tm-field"><span>STO</span><input name="sto" value="${esc(item.sto||'')}"></label><label class="tm-field wide"><span>NAMA RESMI</span><input name="canonical_name" value="${esc(item.canonical_name||'')}"></label><label class="tm-field wide"><span>USERNAME TELEGRAM</span><input name="username" value="${esc(item.username?`@${item.username}`:'')}"></label><label class="tm-field wide"><span>ALIAS NAMA • pisahkan dengan koma</span><input name="aliases" value="${esc((item.aliases||[]).join(', '))}"></label></div><div class="tm-meta">Telegram ID: ${esc(item.telegram_id||'-')}</div><div class="tm-warn">⚠️ Ubah NIK hanya jika memang salah. Sistem akan memigrasikan referensi NIK lama ke NIK baru.</div><button class="tm-save" type="button">SIMPAN & NORMALISASI</button></article>`;}
  function draw(q=''){const host=document.querySelector('#tmList');if(!host||!payload)return;const key=String(q||'').toUpperCase().trim();const rows=(payload.items||[]).filter(i=>!key||`${i.nik} ${i.canonical_name} ${i.username} ${(i.aliases||[]).join(' ')}`.toUpperCase().includes(key));host.innerHTML=rows.map(item=>card(item,(payload.items||[]).indexOf(item))).join('')||'<div class="empty"><p>Teknisi tidak ditemukan.</p></div>';host.querySelectorAll('.tm-save').forEach(btn=>btn.addEventListener('click',()=>saveCard(btn.closest('.tm-card'))));}
  async function saveCard(el){const i=Number(el?.dataset.tmIndex);const item=payload?.items?.[i];if(!item)return;const value=name=>el.querySelector(`[name="${name}"]`)?.value?.trim()||'';const body={telegram_id:userId(),original_nik:el.dataset.originalNik||item.nik||'',nik:value('nik'),canonical_name:value('canonical_name'),username:value('username'),sto:value('sto'),aliases:value('aliases').split(',').map(v=>v.trim()).filter(Boolean)};if(body.original_nik!==body.nik&&!confirm(`Koreksi NIK ${body.original_nik} → ${body.nik}?\nReferensi pekerjaan akan ikut dimigrasikan.`))return;const btn=el.querySelector('.tm-save');btn.disabled=true;btn.textContent='MENYIMPAN...';try{const r=await fetch('/api/technician-master',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||`HTTP ${r.status}`);showToast(body.original_nik!==body.nik?`NIK dikoreksi → ${body.nik}`:`Master ${body.nik} tersimpan`);await refreshOverlay();}catch(e){showToast(`Gagal: ${e.message}`);btn.disabled=false;btn.textContent='SIMPAN & NORMALISASI';}}
  async function runNormalize(){try{const r=await fetch('/api/technician-master/normalize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({telegram_id:userId()})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||`HTTP ${r.status}`);showToast(`${d.total_changed||0} baris dinormalisasi`);await refreshOverlay();}catch(e){showToast(`Normalisasi gagal: ${e.message}`);}}
  async function refreshOverlay(){const d=await loadMaster();const stat=document.querySelector('#tmStat');if(stat)stat.textContent=`${d.items?.length||0} teknisi • akses ${d.role||'MANAGER'} • normalisasi ${d.normalization?.total_changed||0} baris`;draw(document.querySelector('#tmSearch')?.value||'');}
  async function open(){styles();let overlay=document.querySelector('#technicianMasterOverlay');if(!overlay){overlay=document.createElement('section');overlay.id='technicianMasterOverlay';overlay.className='tm-overlay';overlay.innerHTML=`<div class="tm-head"><button id="tmClose">‹</button><div><strong>Master Teknisi</strong><small>NIK • nama resmi • Telegram • username • STO • alias</small></div></div><div id="tmStat" class="tm-stat">Memuat...</div><div class="tm-tools"><input id="tmSearch" placeholder="Cari NIK / nama / username"><button id="tmNormalize">NORMALISASI</button></div><div id="tmList"></div>`;document.body.appendChild(overlay);overlay.querySelector('#tmClose').addEventListener('click',()=>overlay.remove());overlay.querySelector('#tmSearch').addEventListener('input',e=>draw(e.target.value));overlay.querySelector('#tmNormalize').addEventListener('click',runNormalize);}try{await refreshOverlay();}catch(e){overlay.querySelector('#tmStat').textContent=`❌ ${e.message}`;}}
  function ensureButton(){const filter=document.querySelector('#supervisorReportFilter');if(!filter||document.querySelector('#openTechnicianMaster'))return;const b=document.createElement('button');b.id='openTechnicianMaster';b.className='tm-open';b.type='button';b.textContent='👥 MASTER TEKNISI';b.addEventListener('click',open);filter.appendChild(b);}
  styles();ensureButton();new MutationObserver(ensureButton).observe(document.body,{childList:true,subtree:true});window.openTechnicianMaster=open;
})();
